---
- name: Create 'logstash' configuration directory
  file:
    path: /etc/elastic/logstash
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Create 'logstash' config file
  copy:
    src: logstash.conf
    dest: /etc/elastic/logstash/logstash.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart logstash

- name: Configure logstash systemd unit
  template:
    src: logstash.service.j2
    dest: /etc/systemd/system/logstash.service
    owner: root
    group: root
    mode: '0644'
  notify: 
    - reload systemd
    - restart logstash

- name: Flush handlers to ensure unit file is loaded
  meta: flush_handlers

- name: Start and run logstash service
  service:
    name: logstash
    state: started
    enabled: true
