---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart kibana
  service:
    name: kibana
    state: restarted

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted

- name: restart logstash
  service:
    name: logstash
    state: restarted
